xxvethernet: Misc modifications to support SDT based example
Summarized the driver changes:
- Introduce mask for getting connected DMA IP base address from
  XxvDevBaseAddress.
- Remove XxvDevType from XXxvEthernet_Config as it's now derived
  from XxvDevBaseAddress field.
- Fix compilation error in xxxvethernet_sinit.c:83:20: error:
  'XXxvEthernet_ConfigTable' undeclared.
- Add "xlnx,xxv-ethernet-4.0" compatibility string and fix data
  type for axistream-connect property.

Signed-off-by: Radhey Shyam Pandey <radhey.shyam.pandey@xilinx.com>